// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `eu.atchef` namespace.
pub mod recipe;
#[derive(Debug)]
pub struct Recipe;
impl atrium_api::types::Collection for Recipe {
    const NSID: &'static str = "eu.atchef.recipe";
    type Record = recipe::Record;
}
