// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `eu.atchef.recipe` namespace.
use atrium_api::types::TryFromUnknown;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///Recipe content in Cooklang format
    pub content: String,
    pub created_at: atrium_api::types::string::Datetime,
    ///Cover image
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub image: core::option::Option<atrium_api::types::BlobRef>,
    ///Recipe title
    pub name: String,
    ///Number of servings
    pub portions: core::num::NonZeroU64,
    ///Total time in minutes
    pub time: core::num::NonZeroU64,
}
pub type Record = atrium_api::types::Object<RecordData>;
impl From<atrium_api::types::Unknown> for RecordData {
    fn from(value: atrium_api::types::Unknown) -> Self {
        Self::try_from_unknown(value).unwrap()
    }
}
